source=./effects.conf
source=./binds.conf
source=./rules.conf

# Exec once
exec-once=noctalia
exec-once=telegram-desktop
exec-once=steam

# Colors
bordercolor=0x440099ff
focuscolor=0xBB00DDff


# Hotarea
enable_hotarea=1
#hotarea_size=10
hotarea_corner=2

# General
cursor_size=12
cursor_theme=Adwaita
mouse_accel_profile=2
mouse_accel_speed=-0.5

# Master-Stack Layout Setting
new_is_master=0
default_mfact=0.55
default_nmaster=1
tag_num=9
smartgaps=1


# Misc
drag_tile_to_tile=1
xkb_rules_options=compose:ralt


source=~/.config/mango/noctalia.conf
