# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0xf8f9faff
bordercolor = 0x8a9199ff
dropcolor = 0xff8f4080
splitcolor = 0x55b4d4ff
focuscolor = 0xff8f40ff
maximizescreencolor = 0x86b300ff
urgentcolor = 0xe65050ff
scratchpadcolor = 0x55b4d4ff
globalcolor = 0xf7d3baff
overlaycolor = 0xd1f076ff
jump_label_decorate_fg_color = 0x42474cff
jump_label_decorate_bg_color = 0xd9dce0ff
jump_label_decorate_focus_fg_color = 0xf8f9faff
jump_label_decorate_focus_bg_color = 0xff8f40ff
jump_label_decorate_border_color = 0x8a9199ff
group_bar_decorate_fg_color = 0x42474cff
group_bar_decorate_bg_color = 0xd9dce0ff
group_bar_decorate_focus_fg_color = 0xf8f9faff
group_bar_decorate_focus_bg_color = 0xff8f40ff
group_bar_decorate_border_color = 0x8a9199ff
