# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x0b0e14ff
bordercolor = 0x595f6aff
dropcolor = 0xe6b45080
splitcolor = 0x39bae6ff
focuscolor = 0xe6b450ff
maximizescreencolor = 0xaad94cff
urgentcolor = 0xd95757ff
scratchpadcolor = 0x39bae6ff
globalcolor = 0x76530eff
overlaycolor = 0x476111ff
jump_label_decorate_fg_color = 0xd1d1c7ff
jump_label_decorate_bg_color = 0x272c36ff
jump_label_decorate_focus_fg_color = 0x0b0e14ff
jump_label_decorate_focus_bg_color = 0xe6b450ff
jump_label_decorate_border_color = 0x595f6aff
group_bar_decorate_fg_color = 0xd1d1c7ff
group_bar_decorate_bg_color = 0x272c36ff
group_bar_decorate_focus_fg_color = 0x0b0e14ff
group_bar_decorate_focus_bg_color = 0xe6b450ff
group_bar_decorate_border_color = 0x595f6aff
