# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x212337ff
bordercolor = 0x646d8eff
dropcolor = 0x37f49980
splitcolor = 0xa48cf2ff
focuscolor = 0x37f499ff
maximizescreencolor = 0x04d1f9ff
urgentcolor = 0xf16c75ff
scratchpadcolor = 0xa48cf2ff
globalcolor = 0x05733eff
overlaycolor = 0x013f4bff
jump_label_decorate_fg_color = 0xebfafaff
jump_label_decorate_bg_color = 0x31374fff
jump_label_decorate_focus_fg_color = 0x171928ff
jump_label_decorate_focus_bg_color = 0x37f499ff
jump_label_decorate_border_color = 0x646d8eff
group_bar_decorate_fg_color = 0xebfafaff
group_bar_decorate_bg_color = 0x31374fff
group_bar_decorate_focus_fg_color = 0x171928ff
group_bar_decorate_focus_bg_color = 0x37f499ff
group_bar_decorate_border_color = 0x646d8eff
