# Tag Rules
circle_layout = tile,scroller,vertical_scroller,dwindle,fair
tagrule = id:1,layout_name:scroller
tagrule = id:2,layout_name:dwindler
tagrule = id:5,layout_name:monocle

# Window Rules
#new_is_master = 0
windowrule = appid:steam,title:Friends List,width:200,height:50
windowrule = appid:steam,title:Steam,isopensilent:1,tags:4
windowrule = title:Picture in picture,isopensilent:1,isoverlay:1,isfloating:1,isglobal:1,width:450,height:450,offsetx:500,offsety:300
windowrule = appid:org.telegram.desktop,tags:3
windowrule = appid:vivaldi-stable,title:^(?!.*Vivaldi).*$,isfloating:1